title = "EVE新玩家教程"
languageCode = "en-us"

theme = "hugo-theme-learn"
publishdir = "public"
builddrafts = true

[params]
  editURL = "https://github.com/ayust/alpha-guide/edit/master/content/"
  author = "Aaeriele"
  disableLandingPageButton = true
  disableMermaid = true
  disableSearch = true
